# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Researches
    url: '#publications'
    weight: 20
  - name: Teaching
    url: '#posts'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 40
